kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "eureka-build"
spec:
  runPolicy: "Serial" 
  triggers: 
    - type: "ImageChange"
  source: 
    git:
      uri: "REPLACE"
    sourceSecret:
      name: "bitbucket"
  strategy: 
    sourceStrategy:
      from:
        kind: "ImageStreamTag"
        name: "REPLACE"
  output: 
    to:
      kind: "ImageStreamTag"
      name: "eureka:latest"
